name: flutter_chen_refresh
description: A powerful Flutter refresh library with customizable indicators and smooth animations.
version: 3.0.2
homepage: https://github.com/Er-Dong-Chen/flutter_chen_refresh

topics:
  - refresh

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
